### ISSUE TITLE
Version 3.21.0 LIVE updates

### ISSUE THREAD

**Issue by Dymerz** [Dymerz/StarCitizen-Localization#103]
Since few hours the `3.21.0` has been released in LIVE, you can find changed lines in the PR #101 that contains `1,777` lines and `179` new that has been added to the english global.ini

As of a few hours ago, version `3.21.0` has been released live. 
You can find the list of changes in the PR #101 (thanks to @Auhrus ), which contains a total of `1,956` lines, including `179` new lines added to the `english` `global.ini` file.

From now on, new PR will be targeting the 3.21.0 live.

Update status:
  - [x] English
  - [x] French - France
  - [x] German - Germany
  - [x] Italian - Italy
  - [x] Portuguese - Brazil
  - [ ] Spanish - Spain

**Comment by ROBdk97** [comment]
German #121

**Comment by juancmontes** [comment]
Spanish #120

**Comment by Dymerz** [comment]
Italian #135
