### ISSUE TITLE
PYRO-PREVIEW english global.ini

### ISSUE THREAD

**Issue by ROBdk97** [Dymerz/StarCitizen-Localization#138]
[global.ini.txt](https://github.com/Dymerz/StarCitizen-Localization/files/13238808/global.ini.txt)

The English global.ini from the Pyro Technical Preview.

I don't know if this will be helpful soon but here it is. Sadly I don't have access to the 3.21.1 Patch

**Comment by Dymerz** [comment]
I think we should focus on PU and PTU, and completely ignore any other `Preposterously Precarious Prototype` environments that may appear, these env are unstable and I don't know if translations are going to be as is in PU
