### ISSUE TITLE
Localization management in Italian

### ISSUE THREAD

**Issue by Anyma6** [Dymerz/StarCitizen-Localization#186]
Following the merge request #185  I would like to discuss the situation regarding the Italian localization.

Doing manual checks of many lines at each release of a new patch is a big job, which in my opinion penalizes localization for several reasons:

1. This means that by merging the files from time to time, considering that the lines do not coincide with those present in the original English file, any changes made directly on github are canceled. This already happened the first time the file was merged, the various translations we had done by hand were lost in favor of the file with the complete translation into Italian, done automatically and with several errors.

2. Group work is completely eliminated, having to merge each time this file created outside this repository and practically delegated to a single person, who works in a non-shared way.

I would prefer, if possible, that the providers of the Italian file make the changes directly here, so that other people can actively participate in the translation, as it should be.

This month my translation team and I have temporarily paused translations for this reason, making work difficult.

I think we need to discuss how to address this problem

**Comment by ROBdk97** [comment]
Why didn't you tell me the first time that there was an issue with the Italian translation? I have now closed the pull request.

I tried to convince the guy to contribute here on GitHub but he just said that he doesn't know how to use GitHub and that he does not want to use it for this reason.

I just tried to help with the Italian translation because the current live build was still not supported.
I even spent hours trying to fix the file because it is a freaking mess all the time. Duplicate entries, in a different line, and so on.

I will now ignore any updates from GattoMatto and MrRevo if they are not in this repo.

Sorry for the inconvenience.

**Comment by Anyma6** [comment]
Don't worry, I wasn't accusing anyone, on the contrary, I exposed the problem to find a solution together.

MrRevo and GattoMatto update the file every time when new patches are released, which is "my" limit, in the sense that we were working to find a way to automatically add new lines to the file.

**Comment by ROBdk97** [comment]
I currently use my program which sorts the keys to the same position as in the English version and if it finds duplicates it asks which one to use. But I should probably also add a check for the placeholders if they are missing or not.

It's just difficult to do this for Italian as I don't speak Italian. I understand some words and so on but that's not enough to do this probably.

**Comment by ROBdk97** [comment]
I can put it on GitHub later. It's still a work in progress and a bit chaotic though. Will notify you if it's Up

**Comment by ROBdk97** [comment]
Just a Simple C# Console App without top-level-statements with .Net7

And after this is done I use WinMerge or the GitHub client to compare the old and new Version of the Language global.ini and translate the Lines Manually.

```cs
using System.Text;

Console.WriteLine("Enter the path to the input file (EN):");
string inputFilePath = Console.ReadLine();
inputFilePath = inputFilePath.Replace("\"", "");
Console.WriteLine("Enter the path to the output file (de, es, ...):");
string langFilePath = Console.ReadLine();
langFilePath = langFilePath.Replace("\"", "");
await AddMissingEntries(inputFilePath, langFilePath);
Console.WriteLine("Done!");
Console.WriteLine("Press Enter to exit...");
Console.ReadLine();

static async Task AddMissingEntries(string inputFilePath, string outputFilePath)
{
    var readIn = Task.Run(() => File.ReadAllLinesAsync(inputFilePath));
    var readOut = Task.Run(() => File.ReadAllLinesAsync(outputFilePath));

    var file1Lines = await readIn;
    var file2Lines = await readOut;

    Console.WriteLine("Checking for duplicates in file 1");
    file1Lines = await CheckDuplicates(file1Lines);

    Console.WriteLine("Checking for duplicates in file 2");
    file2Lines = await CheckDuplicates(file2Lines);

    // get a dictionary of all keys with P
    var keysWithP = file2Lines
        .Select(line => line.Split(new[] { '=' }, 2))
        .Where(split => split.Length == 2 && split[0].EndsWith("P"))
        .GroupBy(split => split[0])
        .ToDictionary(group => group.Key, group => group.FirstOrDefault()?[1] ?? "");

    // get a dictionary of all keys and values from file1
    var file1Dict = file1Lines.Select(line => line.Split('=', 2)).ToDictionary(split => split[0], split => split[1]);

    // get a dictionary of all keys and values from file2
    var file2Dict = file2Lines
        .Select(line => line.Split(new[] { '=' }, 2))
        .Where(split => split.Length == 2)
        .GroupBy(split => split[0])
        .ToDictionary(group => group.Key, group => group.FirstOrDefault()?[1] ?? "");

    // check if the key is in file1 without ,P and add it to file2
    foreach(var line in keysWithP)
    {
        var key = line.Key.Replace(",P", "");
        if(!file1Dict.ContainsKey(key))
        {
            file2Dict[key] = line.Value;
        }
    }
    var outputBuilder = new StringBuilder();

    // Go over file1 and add the values from file2 if they exist else add the line from file1
    foreach(var line in file1Lines)
    {
        var key = line.Split('=')[0];
        if(file2Dict.TryGetValue(key, out string? value))
            outputBuilder.AppendLine($"{key}={value}");
        else
        {
            Console.WriteLine($"Adding line {key}: {file1Dict[key]}");
            outputBuilder.AppendLine(line);
        }
    }
    await File.WriteAllTextAsync(outputFilePath, outputBuilder.ToString(), new UTF8Encoding(true));
}

// Check for duplicates and ask the user to choose one
static Task<string[]> CheckDuplicates(string[] lines)
{
    var keyValuePairs = new Dictionary<string, List<string>>();

    // First pass to group values by keys
    foreach(var line in lines)
    {
        var parts = line.Split('=');
        var key = parts[0];
        var value = parts.Length > 1 ? parts[1] : "";

        if(!keyValuePairs.ContainsKey(key))
        {
            keyValuePairs[key] = new List<string>();
        }
        keyValuePairs[key].Add(value);
    }

    // User interaction for duplicates
    foreach(var pair in keyValuePairs)
    {
        if(pair.Value.Count > 1)
        {
            // dont ask if they are the same
            if(pair.Value.Distinct().Count() == 1)
            {
                keyValuePairs[pair.Key] = new List<string> { pair.Value[0] };
                continue;
            }
            Console.WriteLine($"Multiple values found for key '{pair.Key}'. Please choose one:");
            for(int i = 0; i < pair.Value.Count; i++)
            {
                Console.WriteLine($"{i + 1}: {pair.Value[i]}");
            }

            int choice;
            do
            {
                Console.Write("Enter the number of the value you want to keep: ");
            } while (!int.TryParse(Console.ReadLine(), out choice) || choice < 1 || choice > pair.Value.Count);

            // Keep only the chosen value
            keyValuePairs[pair.Key] = new List<string> { pair.Value[choice - 1] };
        }
    }
    // Construct the final list of lines
    var finalLines = keyValuePairs.SelectMany(pair => pair.Value.Select(value => $"{pair.Key}={value}")).ToList();

    // Return the final list
    return Task.FromResult(finalLines.ToArray());
}
```

**Comment by ROBdk97** [comment]
Can we close this issue?

**Comment by Anyma6** [comment]
sure

**Comment by ROBdk97** [comment]
I updated the Code as it had some issues.
- Now re-uses existing translation if ",P" got removed or added
- splits the line correctly so that if an additional "=" exits in the line the part after it does not get lost
