### ISSUE TITLE
Language without () does not work

### ISSUE THREAD

**Issue by ROBdk97** [Dymerz/StarCitizen-Localization#2]
**Issue Description:**

I experimented with the language settings and noticed an inconsistency in the way they are recognized. The format without parentheses doesn't seem to work, while the one with parentheses does. Additionally, the examples provided in the documentation table appear to be incorrect.

**Examples:**

**Not Working:**
g_language = german

**Working:**
g_language = german_(germany)

Please review the documentation and correct the examples accordingly.

**Comment by Dymerz** [comment]
Okay, good to know, I will update the documentation

**Comment by ROBdk97** [comment]
btw. I also added a german Readme
