### ISSUE TITLE
German Alternative Translation 

### ISSUE THREAD

**Issue by ROBdk97** [Dymerz/StarCitizen-Localization#27]
I found an alternative German translation but it has a lot of differences some translations aren't as good and some are better.
Too many differences for one person to manage.
[global_ger_alternative.txt](https://github.com/Dymerz/StarCitizen-Localization/files/12899109/global_ger_alternative.txt)

**Comment by Auhrus** [comment]
Oha where did you find the really is not bad but it would be a lot to check. :(

**Comment by ROBdk97** [comment]
Somebody uploaded it to a file host page and linked it on Spectrum without any source

**Comment by ROBdk97** [comment]
I found another really active Repo for a German Translation. I asked them if they would like to Collaborate.
https://github.com/rjcncpt/StarCitizen-Deutsch-INI

**Comment by ROBdk97** [comment]
I don't know what their problem is. They seem to want to do their own thing... They're just typical Knebel people. xD

**Comment by Auhrus** [comment]
> I don't know what their problem is. They seem to want to do their own thing... They're just typical Knebel people. xD

Yes, okay then not.  I just find it unnecessary if everyone cooks their own soup.  It's more work for everyone.  😪😮‍💨

**Comment by ROBdk97** [comment]
I agree with you on that.
