### ISSUE TITLE
It seems some strings are still missing in the extracted globals.ini

### ISSUE THREAD

**Issue by syntafin** [Dymerz/StarCitizen-Localization#3]
First at all, nice idea to create a repo for this.
And! Nice work from @ROBdk97 with the german translation so far! (Some string may need a better one, but damn... everything seems to be translated so far as possible).

What I saw in a short test is, that some string seems to be missed at all (I didnt find them in the file at all):
![image](https://github.com/Dymerz/StarCitizen-Localization/assets/695535/bddb57bf-3ed1-4b09-8796-c916dddc8df2)
![image](https://github.com/Dymerz/StarCitizen-Localization/assets/695535/27f87e11-ec45-42aa-ad30-205c0c0e74db)

FYI: The missing namens in the Main menu friendlist is no bug, I removed them for privacy reasons with AI :) .

May will be a good idea to keep a track in the repo of missing strings, then we may can add them.

**Comment by ROBdk97** [comment]
Thank you for bringing this to my attention. I'm currently working on addressing the issue. I've also noticed the problem and have made corrections to some translation errors. Additionally, I've identified and fixed issues with entries like ~mission(SOMETHING).

**Comment by ROBdk97** [comment]
In the file, the German version has 68952 lines, while the English version has 68949 lines. I'm unsure about the discrepancy of the extra 3 lines in the German version.

**Comment by Dymerz** [comment]
In this goal, I'm working on a "Status Checks" on PR to check for any missing translations

**Comment by ROBdk97** [comment]
I think we still miss the Release for my changes in Pull Request #5

**Comment by Dymerz** [comment]
Indeed, released! 🚀
(Also looking for a better way to automate releases)

**Comment by ROBdk97** [comment]
@syntafin Would you like to Close the Issue or is there anything else?

**Comment by syntafin** [comment]
For the moment we can close this one :)
