### ISSUE TITLE
Zusammen bringen von  NofaceIggy und eurer global.ini

### ISSUE THREAD

**Issue by robokalle** [Dymerz/StarCitizen-Localization#31]
Hallo zusammen,
NofaceIggy hat gute Sachen drinn wie Tür offnen und bei Objekte handhabung.
Ihr habt Umlaute im Text auch das mit dem Annehmen von Meldungen das es "+" ist usw.
Wie kann man mit helfen das sowas von einem zum anderen mit eingepflegt werden kann.

Eigennamen z.B. von Waffen würde ich in englisch lassen.

**Comment by ROBdk97** [comment]
Ich hab schon daran gearbeitet die Items am besten englisch zu lassen abgesehen von der Farbe und welches teil es ist (Arme, Helm, Beine, ...) weil ich finde das ist an der stelle nicht relevant weil das ist ja nicht der name direkt.
Beispiel: "ADP Arms Black", jeder weiß was mit APD gemeint ist und der rest sind Zusätze wo das Objekt genauer beschreiben.
(Abgesehen von dem Beispiel das man APD nicht übersetzen kann)

**Comment by robokalle** [comment]
Hallo hier mal noch ein paar anpassungen:

innerthought_inspect=Inspizieren
interaction_carry=Tragen
interaction_carry_lowered=Trage abgesenkt
interaction_condition_InProne=Ausstieg in Bauchlage
interaction_condition_exitSeat=Sitzplatz verlassen
interaction_drink=Trinken
interaction_drop=Fallen lassen
interaction_grab=Greifen
interaction_grip=Griff
interaction_liedown=Hinlegen
interaction_liedown_top=oben hinlegen
interaction_open=Öffnen
interaction_push=Druecken
interaction_situp=Aufstehen
interaction_sleep=Schlaf
interaction_store=Einpacken
interaction_stow=Verstauen
interaction_swap=Tauschen
interaction_toggleEquipHelmet=Helm auf/absetzen
interaction_togglelights,P=Lichter umschalten
ui_interactor_carry=Nehmen
ui_interactor_close=Schließen
ui_interactor_close_Interior=Innenraum schließen
ui_interactor_close_copilot_canopy=Copilot Cockpithaube schließen
ui_interactor_close_pilot_canopy=Cockpithaube schließen
vehicle_interactor_SubTarget_Engines=Ziel-Triebwerken
vehicle_interactor_Turret_Deploy=Geschützturm ein
vehicle_interactor_Turret_Retract=Geschuetzturm einfahren
vehicle_interactor_UnPinTarget=Ziel lösen
vehicle_interactor_WeaponRack_Deploy=Lenkflugkörper ausfahren
vehicle_interactor_WeaponRack_Retract=Lenkflugkörper einfahren
weapon_stats_unit_rpm=U/min

vehicle_interactor_CountermeasureFire=Täuschkörper aktivieren
vehicle_interactor_CountermeasureType_Chaff=Radar-Störkörper
vehicle_interactor_CountermeasureType_Flare=IR-Täuschkörper
vehicle_interactor_Coupled_Enable=Gekoppelten Flug aktivieren

**Comment by ROBdk97** [comment]
Kannst du das nicht selbst ändern in der Datei oder weißt du nicht wie GitHub funktioniert?

**Comment by robokalle** [comment]
Das Letztere. Habe bei GitHub noch nie was geändert.

**Comment by ROBdk97** [comment]
Ich arbeite dran^^

**Comment by ROBdk97** [comment]
Hey schau mal bei #41 rein hier hab ich deine Änderungen in teilweise leicht abgewandelter Version hinzugefügt.
Hoffe das passt so.

**Comment by ROBdk97** [comment]
This Issue can be closed!
