### ISSUE TITLE
French Github Repo Collab?

### ISSUE THREAD

**Issue by ROBdk97** [Dymerz/StarCitizen-Localization#8]
I found a French GitHub Repo maybe we should merge/collaborate?
https://github.com/SPEED0U/StarCitizenTranslations/ 

And how about a Spectrum Post? Maybe we get highlighted xD

**Comment by Dymerz** [comment]
Nice find 🚀
That a great idea, I will definitely do that!

**Comment by Dymerz** [comment]
I just published on Spectrum: https://robertsspaceindustries.com/spectrum/community/SC/forum/3/thread/centralizing-localization-efforts
