### ISSUE TITLE
Italian

### ISSUE THREAD

**Issue by ROBdk97** [Dymerz/StarCitizen-Localization#81]
https://robertsspaceindustries.com/spectrum/community/SC/forum/50172/thread/localization-italian/6274646

```
Wolverine@GattoMatto
here is the file. Please add me and MrRevo as reference 
https://drive.google.com/file/d/1Fm9KAcOAzK0THj_wAki32ibhAgRmTYG3/view?usp=sharing
```

**Comment by Anyma6** [comment]
I'm trying to download the file but it says it's in the owner's trash...

It would be a great thing to merge the works, even if there would be many lines to double check.

**Comment by ROBdk97** [comment]
The Italian file is on this page and we also collaborate with them I think?
https://sctranslator.danidomen.com/

**Comment by Anyma6** [comment]
I didn't know about it! I immediately propose it to our translators, I imagine it is a machine translation job. We translated many lines manually, let's try to understand how to combine the works!

@Dymerz are we collaborating with them?

**Comment by ROBdk97** [comment]
Well this repo mentioned on their page^^

**Comment by Anyma6** [comment]
I'm checking by phone, in the late afternoon I should have time to check better, I saw that the Italian translations are completely automatically generated.

On the one hand I would hate to lose the work done so far, given that we are translating every single line by hand, on the other I understand that this is a "ready" work even if with several errors.

Merging the two works would require manually checking all the lines translated so far I guess, we'll see what to do

**Comment by Dymerz** [comment]
@Anyma6, I'm not collaborating with them at the moment, and I don't know if they are working on any translations on their end. I should reach out to them.

Moreover, manual translations are usually better than AI. If possible, I will merge the two files, prioritizing the human-translated content first. I'm already doing this with the French translation using the [Update French action](https://github.com/Dymerz/StarCitizen-Localization/blob/main/.github/workflows/update-french.yaml)

**Comment by ROBdk97** [comment]
Finally got the italian file.
We should mention both Wolverine and MrRevo as wished by Wolverine.

**Comment by Dymerz** [comment]
Good, I made the mention on the [README.md](https://github.com/Dymerz/StarCitizen-Localization#readme)
